/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/o-kancelarii': RouteRecordInfo<'/o-kancelarii', '/o-kancelarii', Record<never, never>, Record<never, never>>,
    '/oferta/': RouteRecordInfo<'/oferta/', '/oferta', Record<never, never>, Record<never, never>>,
    '/oferta/prawo-administracyjne': RouteRecordInfo<'/oferta/prawo-administracyjne', '/oferta/prawo-administracyjne', Record<never, never>, Record<never, never>>,
    '/oferta/prawo-cywilne': RouteRecordInfo<'/oferta/prawo-cywilne', '/oferta/prawo-cywilne', Record<never, never>, Record<never, never>>,
    '/oferta/prawo-karne': RouteRecordInfo<'/oferta/prawo-karne', '/oferta/prawo-karne', Record<never, never>, Record<never, never>>,
    '/oferta/prawo-pracy': RouteRecordInfo<'/oferta/prawo-pracy', '/oferta/prawo-pracy', Record<never, never>, Record<never, never>>,
    '/oferta/prawo-rodzinne': RouteRecordInfo<'/oferta/prawo-rodzinne', '/oferta/prawo-rodzinne', Record<never, never>, Record<never, never>>,
    '/oferta/prawo-spadkowe': RouteRecordInfo<'/oferta/prawo-spadkowe', '/oferta/prawo-spadkowe', Record<never, never>, Record<never, never>>,
    '/polityka-prywatnosci': RouteRecordInfo<'/polityka-prywatnosci', '/polityka-prywatnosci', Record<never, never>, Record<never, never>>,
  }
}
